S6App/urls.py
from django.urls import path
from . import views

app_name = 'S6App'

urlpatterns = [
    path('', views.landing, name='landing'),
    path('books/', views.books, name='books'),
    path('books/getJson/<str:query>', views.getJson, name='getJson'),
    path('login/', views.loginView, name='login'),
    path('login/welcome', views.welcome, name='welcome'),
    path('logout/', views.logoutView, name='logout'),
]

projectS6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('S6App.urls', namespace="S6App")),
	]

S6App/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class PostMood(models.Model):
	mood = models.CharField(max_length = 300)
	created_date = models.DateTimeField(auto_now_add = True)
	
	def __str__(self):
		return "{}.{}".format(self.id, self.mood)

S6App/forms.py
from django import forms
from .models import PostMood

class MoodForm(forms.ModelForm):
	class Meta:
		model = PostMood
		fields = [
			'mood',
		]
		
		labels = {
			'mood':'Your mood rn: ',
		}
		
		widgets = {
			'mood':forms.TextInput(
				attrs = {
					'class':'form-control',
					'placeholder':'happy as a unicorn :D'
				}
			),
			'created_date':forms.DateTimeInput(
				attrs = {
					'class':'form-control',
				}
			),
		}

S6App/views.py
from django.shortcuts import render, redirect
from .forms import MoodForm
from .models import PostMood
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse
import json
import requests

def landing(request):
    mood_form = MoodForm(request.POST or None)
    if request.method == "POST":
        if mood_form.is_valid():
            mood_form.save()
            return redirect('/')
    else:
        mood_form = MoodForm()
            
    posts = PostMood.objects.all()
	
    contexts = {
        'posts': posts,
        'mood_form': mood_form,
    }
    
    return render(request, 'landing.html', contexts)

def books(request):
    return render(request, 'books.html')

def getJson(request, query):
    url = 'https://www.googleapis.com/books/v1/volumes?q=' + query
    json_data = json.loads(requests.get(url).text)
    return JsonResponse(json_data)

def loginView(request):
    if request.method == "POST":
        username_login = request.POST['username']
        password_login = request.POST['password']
        user = authenticate(request, username=username_login, password=password_login)
        if user is not None:
            login(request, user)
            return redirect('S6App:welcome')
        else:
            return redirect('S6App:login')

    return render(request, 'login.html')

def welcome(request):
    return render(request, 'welcome.html')

def logoutView(request):
    if request.method == "POST":
        print(request.POST)
        if request.POST["logout"] == "yes":
            logout(request)
        return redirect('S6App:landing')
    return render(request, 'logout.html')

S6App/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" id="theme" href="{% static 'css/style.css' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"> </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    </head>

    <body style="padding-top: 65px;">
        <nav class="navbar fixed-top navbar-expand-lg navbar-light" style ="background-color: rgba(160, 83, 115, 0.9);">
            <a class="navbar-brand" style="font-size: 23px;" href="{% url 'S6App:landing' %}">&#x1f325; OurMoodBoard</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'S6App:landing' %}" style="color: white;">HOME<span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'S6App:books' %}" style="color: white;">BOOKS</a>
                    </li>
                </ul>
                <div class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <p style="font-size: 15px; text-align: center; color: white; margin: 10px 20px;">You are logged in as {{user}}.</p>
                        <a type="button" class="btn btn-light" id="logout" href= "{% url 'S6App:logout' %}">LOGOUT</a>
                    {% else %}
                        <a type="button" class="btn btn-light" id="login" href= "{% url 'S6App:login' %}">LOGIN</a>
                    {% endif %}
                </div>
            </div>
        </nav>

        {% block content %}

        {% endblock %}

    </body>
</html>

S6App/templates/books.html
{% extends 'base.html' %}
{% load static %}

{% block title %}BOOKS{% endblock %}

{% block content %}
    <div style="margin-top: 30px">
        <h1 id = "heading" class="d-flex justify-content-center" style="text-align: center">Find Your Favorite Books Here! &#x1f4d6;</h1>
    </div>

    <div class="d-flex justify-content-center">
        <div class="form-group" style="margin-top: 30px;">
            <input id="search-box" class="form-control" placeholder="enter book title or author">
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="form-group">
            <button id="search-button" class="btn btn-primary">Search Book</button>
        </div>
    </div>

    <div class="table-responsive" style="margin-top: 36px">
        <table class="table table-fixed">
            <thead class="text-center">
                <tr>
                    <th scope="col" id="head">#</th>
                    <th scope="col" id="head">Cover</th>
                    <th scope="col" id="head">Title</th>
                    <th scope="col" id="head">Author</th>
                    <th scope="col" id="head">Details</th>
                </tr>
            </thead>
    
            <tbody id="books-table" class="text-center">
            </tbody>
        </table>
    </div>

{% endblock %}

S6App/templates/landing.html
{% extends 'base.html' %}
{% load static %}

{% block title %}MOODBOARD{% endblock %}

{% block content %}
	<div style="margin-top: 30px">
		<h1 id = "heading" class="d-flex justify-content-center" style="text-align: center">Hello! Describe your mood below &#x1F63A</h1>
	</div>
	<div class="d-flex justify-content-center" style="margin-top: 15px">
		<form class="needs-validation" novalidate id="formulir" method='POST'>
			{% csrf_token%}
			{% for form in mood_form %}
			<div class="form-group">
				{{form.label}}
				{{form}}
				<div class="valid-feedback">
					Looks good!
				</div>
				<div class="invalid-feedback">
					This field is required.
				</div>
			</div>
			{% endfor %}
			<div class="d-flex justify-content-center">
				<button class='btn btn-primary' type="Submit" id="submit">Submit</button>
			</div>
		</form>
	</div>
	
	<div class="table-responsive" style="margin-top: 36px">
		<table class="table table-hover">
			<thead>
				<tr>
					<th scope="col" id="head">#</th>
					<th scope="col" id="head">Moods</th>
					<th scope="col" id="head">Date & Time</th>
					<th scope="col" id="head"> </th>
				</tr>
			</thead>

			<tbody>
				{% for post in posts%}
				<tr class = "success">
					<th scope="row" id="head">{{forloop.counter}}</th>
					<td>{{post.mood}}</td>
					<td>{{post.created_date}}</td>
					<td style="font-size: 24px"> &#x2728 </td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>

	<script>
		(function() {
			'use strict';
			window.addEventListener('load', function() {
				// Fetch all the forms we want to apply custom Bootstrap validation styles to
				var forms = document.getElementsByClassName('needs-validation');
				// Loop over them and prevent submission
				var validation = Array.prototype.filter.call(forms, function(form) {
					form.addEventListener('submit', function(event) {
					if (form.checkValidity() === false) {
						event.preventDefault();
						event.stopPropagation();
					}
					form.classList.add('was-validated');
					}, false);
				});
			}, false);
		})();
	</script>

{% endblock %}

S6App/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %} 
{% load static %}

{% block title %}LOGIN{% endblock %}

{% block content %}

<div class="vh-100" style="margin-top: 30px;">
    <div>
        <h1 class="text-center">Let's log yourself in right here &#x1F447;&#x1F3FC;</h1>
        <p class="text-center">If you don't have an account yet, you can contact me by email at
        alfatianisa@gmail.com</p>    
    </div>
    <div class="d-flex justify-content-center" style="margin-top: 30px">
		<form class="needs-validation" novalidate id="formulir" method='POST'>
            {% csrf_token %}
            <div class="form-group">
                <label for="username"><strong>Username: </strong></label>
                <input type="text" class="form-control" name="username" id="username" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
                <div class="invalid-feedback">
                    This field is required.
                </div>
            </div>
            <div class="form-group">
                <label for="password"><strong>Password: </strong></label>
                <input type="password" class="form-control" name="password" id="password" required>
                <div class="valid-feedback">
                    Looks good!
                </div>
                <div class="invalid-feedback">
                    This field is required.
                </div>
            </div>
            <div class="d-flex justify-content-center">
                <button class='btn btn-primary' type="Submit" id="submit">Login</button>
            </div>
        </form>
    </div>
</div>

<script>
		(function() {
			'use strict';
			window.addEventListener('load', function() {
				// Fetch all the forms we want to apply custom Bootstrap validation styles to
				var forms = document.getElementsByClassName('needs-validation');
				// Loop over them and prevent submission
				var validation = Array.prototype.filter.call(forms, function(form) {
					form.addEventListener('submit', function(event) {
					if (form.checkValidity() === false) {
						event.preventDefault();
						event.stopPropagation();
					}
					form.classList.add('was-validated');
					}, false);
				});
			}, false);
		})();
	</script>

{% endblock %}

S6App/templates/logout.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block title %}LOGOUT?{% endblock %}

{% block content %}

<div class="vh-100" style="margin-top: 150px;">
    <div>
        <h1 class="text-center">Hi {{user}},</h1>
        <h2 class="text-center">Are you sure you want to log out? &#x1F937;&#x1F3FB;</h2>
    </div>
    <form method="POST" class="d-flex justify-content-center align-items-center;">
        {% csrf_token %}
        <button style="margin-top: 20px;" type="submit" name="logout" class="btn btn-primary mx-auto mt-2" style="height:42px" value="yes">Yes, I am sure</button>
    </form>
</div>

{% endblock %}

S6App/templates/welcome.html
<!DOCTYPE html>
{% extends 'base.html' %} 
{% load static %}

{% block title %}WELCOME!{% endblock %}

{% block content %}

<div class="vh-100" style="margin-top: 150px;">
    <div>
        <h1 class="text-center">WELCOME {{user}}! &#x1F44B;&#x1F3FC;</h1>
        <p class = "text-center">
            Hope you have been feeling great today!<br>Feel free to share your mood right here. 
        </p>
    </div>
    <a class="d-flex justify-content-center align-items-center" href= "{% url 'S6App:landing' %}">
        <button type="button" class="btn btn-primary mx-auto mt-2" style="height:42px">Back to Homepage</button>
    </a>
</div>

{% endblock %}